version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SESSION_SECRET=your-secret-key-change-this
      - DATABASE_URL=postgresql://postgres:password@db:5432/bloom_flow
      - FLASK_ENV=production
    depends_on:
      - db
    volumes:
      - .:/app
    command: gunicorn --bind 0.0.0.0:5000 --workers 2 --reload main:app

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=bloom_flow
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: